### ISSUE TITLE
Task7 ultima cerinta

### ISSUE THREAD

**Issue by alexandra2607** [UPB-FILS/sde#1]
Buna seara!

Am incercat de mai multe ori sa rezolv ultima cerinta, dar de fiecare data imi spune ca fisierul intermediar boo.o nu este creat. Am verificat mereu directorul task7 si boo.o era existent. 
Credeti ca ar putea fi o problema la checker?

**Comment by RaduNicolaeEduard** [comment]
Aceeasi problema o am si eu
Am generat ambele fisieree intermediare (boo.o, boo.s) prin 2 comenzi, sunt curios daca trebuie facut acest task doar printr-o singura comanda.

**Comment by serban-razvan** [comment]
Hello,

Sorry for the problem you have encountered. We have found a bug in our checker and fixed it just now.

In order to update the checker, run `sudo uso update` and the homework will be updated (you can try to do the `sudo uso check` again and see that the issue should be gone

Let me know if there are any other more issues.



> 
> 
> Aceeasi problema o am si eu
> Am generat ambele fisieree intermediare (boo.o, boo.s) prin 2 comenzi, sunt curios daca trebuie facut acest task doar printr-o singura comanda.

The number of commands given does not matter. Feel free to use as many as you need.

**Comment by alexandra2607** [comment]
Multumim!

**Comment by RaduNicolaeEduard** [comment]
Thank You! 😄
