### ISSUE TITLE
[ Busy-Box ] Invalid chmod / command , errors

### ISSUE THREAD

**Issue by RaduNicolaeEduard** [UPB-FILS/sde#21]
So, we are supposed to print Invalid command, and than exit with -1 (255).

Is there something wrong here?

![Screenshot from 2020-03-15 12-07-13](https://user-images.githubusercontent.com/61273664/76699422-fdb78d00-66b5-11ea-9274-b08bfafb3c31.png)

**Comment by philip31** [comment]
this is the code that will test the output

if [ $scriptresult != 1 ]
    then
        echo 'Script does not return 1 when command is not correct.' > $testfile
        exit -1
    fi

as i can see, the script is testing whether the output is 1 or not. So i think the script is wrong.. :(. Hope it will get corrected soon

**Comment by ioanaculic** [comment]
The checker is updated. I also pushed the changes on github now.

The problem is that the write buffer does not get flushed all times and sometimes the text is not written at stdout.

There are two solutions for this:
1. use `print ("Invalid command", flush=True)`
2. use `exit (-1)` instead of `os._exit (-1)`

**Comment by RaduNicolaeEduard** [comment]
Thank You! 
It Works :+1:
