### ISSUE TITLE
I'am Popa Alexandru from 1221F ! I need help with the checker !

### ISSUE THREAD

**Issue by AlexandruCristian2312** [UPB-FILS/sde#4]
Do I have to give sudo uso update checker  again before submitting the last time the homework 1 at Sde? You mean the checker needs to be updated to make sure the score is correct ?

**Comment by serban-razvan** [comment]
Not necessarily, but because for a part of the last exercise the checker doesn't give points for the correct solve, I'd say that an update should be done. If you managed to get all the points while having the non-updated checker, then it's all good (in that case, please let me know how you did it because as far as I know there isn't any conceivable way of solving the last exercise with the checker giving the points, only if the checker was already updated when you did ```sudo uso start 1```)
