### ISSUE TITLE
[Homework 1, Task 5] Issue with vmchecker

### ISSUE THREAD

**Issue by iulianduminica** [UPB-FILS/sde#6]
When trying to create the Evil $pirits file, even if i use "Evil $pirits" or "Evil$pirits", the vmchecker will say that it was not created correctly. I finished making the rest of the files and folders, but when going back to fix that file, I'm stuck with 12p because it is not deemed correct.

Meanwhile, renaming the file at Task 6 is somehow right and I receive all the points. 

In the attached picture it can be seen that I created both variants of the file but somehow something is still not right. Thanks in advance!

https://i.imgur.com/bM8WkdJ.png
https://i.imgur.com/PtN7jYD.png

**Comment by serban-razvan** [comment]
Hello,

Sorry for the problems you have, but (referring to the first picture) by giving the command 'ls' into folder 'Halloween/The Nun', I can only see some folders named 'Evil' or 'Evil ' (notice the space). The '$pirits' part is missing. 

You are on the right way to solve the exercise, but as an advice, fiddle with the quotes in order to get the result you want (have also the $pirits part)

**Comment by iulianduminica** [comment]
Your advice regarding the quotes was the part I was doing wrong; managed to fix the problem, thank you!
